### ISSUE TITLE
drop only one card at time

### ISSUE THREAD

**Issue by aleff-github** [bronzodile/Freecell#1]

**Comment by bronzodile** [comment]
Hi Alessandro,
Sorry, I couldn't understand what is this issue about.
Could you describe it in more detail please? Maybe a screenshot or a short recording?
Thanks!

**Comment by aleff-github** [comment]
when you try to shift more than one card it doesn't... try to shift something like 7-6-5 to an 8 you will see that you shift just the 7

**Comment by bronzodile** [comment]
This issue should be resolved now.
